CREATE OR REPLACE FUNCTION FN_AH_DIAS_REC_ABSOLUCION(P_RECCOD IN VARCHAR, P_FECHOY IN DATE)
RETURN NUMBER IS

ln_DIAS NUMBER(9);
lv_ERRCOD VARCHAR(3);
lv_ERRMSG VARCHAR(600);

BEGIN
PQ_AH_REC_DIAS_CONT.SP_AH_GEN_DIAS_ABSOLUCION(P_RECCOD, P_FECHOY, ln_DIAS, lv_ERRCOD, lv_ERRMSG);
RETURN ln_DIAS;

END FN_AH_DIAS_REC_ABSOLUCION;
/

