CREATE OR REPLACE FUNCTION FN_CR_TOKENIZADO_SHA1(INPUT VARCHAR2)
RETURN CHAR PARALLEL_ENABLE
IS
  LC_RPTA CHAR(40);
BEGIN
  LC_RPTA := DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW('rU'||INPUT||'1d0'), SYS.DBMS_CRYPTO.HASH_SH1);
  RETURN LC_RPTA;

EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
END;
/

