CREATE OR REPLACE FUNCTION "FN_MAIL" ( NROCTA IN VARCHAR2)
RETURN VARCHAR2 IS
MAIL VARCHAR2(1000);
BEGIN
     MAIL := '';
     FOR L_MAI IN (SELECT TRIM(CTXTXT) CTXTXT FROM FSX008 WHERE CTNRO=NROCTA)  LOOP
         MAIL := L_MAI.CTXTXT ||' | '|| MAIL;
     END LOOP;
     RETURN MAIL;
END;
/

