CREATE OR REPLACE FUNCTION "FN_TELCLIE" (NUMDOC IN VARCHAR2)
RETURN VARCHAR2 IS
TELEFONOS VARCHAR2(10000);
BEGIN
     TELEFONOS := '';
     FOR L_TEL IN (SELECT DOTELFP TEL FROM FSR005  WHERE PENDOC= rpad(NUMDOC,12,' ')) LOOP
         TELEFONOS := L_TEL.TEL ||' | '|| TELEFONOS;
     END LOOP;
     RETURN TELEFONOS;
END;
/

