create or replace force view jaql374 as
select
"ID_REGISTRO" "JAQL374IDREG",
"APLICACION" "JAQL374APLIC",
"COD_VENTANA" "JAQL374CODVE",
"HORA_INICIO_REGIS" "JAQL374HINIR",
"HORA_FIN_REGIS" "JAQL374HFINR",
"HORA_INICIO_ENVIO" "JAQL374HINIE",
"HORA_FIN_ENVIO" "JAQL374HFINE",
"REG_STATUS" "JAQL374RGSTA",
"COD_SESION" "JAQL374CODSE"
from  CANJEINTBANPR.TABVENTANATIEMPO;

