create or replace force view jaql381 as
select
"COD_SESION" "JAQL381CDSES",
"COD_PROCESO"	"JAQL381CDPRO",
"HORA_INI_REG" "JAQL381HRIRE",
"HORA_FIN_REG" "JAQL381HRFRE",
"HORA_INI_ENV" "JAQL381HRIEN",
"HORA_FIN_ENV" "JAQL381HRFEN",
"USU_ACT" "JAQL381USACT",
"FCH_ACT" "JAQL381FCACT",
"HORA_ACT" "JAQL381HRACT"
from TRANSFINTBANPR.TRF_VENTANAHORARIA;

