CREATE OR REPLACE FORCE VIEW JAQL373 AS
SELECT
  ID_ITEM     "JAQL373IDITE",
  CODTABLA    "JAQL373CODTA",
  CODITEM     "JAQL373CODIT",
  DESCRIPCION "JAQL373DSCRI",
  SHORTDESC   "JAQL373SHODS",
  REG_STATUS  "JAQL373REGST"
  FROM CANJEINTBANPR.DATOSTABLA;

