create or replace force view jaql382 as
select
"CANAL" "JAQL382CANAL",
"DESCRIPCION" "JAQL382DESCR",
"DESC_SHORT" "JAQL382DSCSH",
"STATUS" "JAQL382STATU",
"USU_ACT" "JAQL382USACT",
"FCH_ACT" "JAQL382FCACT",
"HORA_ACT" "JAQL382HRACT"
from TRANSFINTBANPR.TRF_CANAL;

