create or replace force view jaql371 as
select
"CODBAN"	"JAQL371CODBA",
"AGENCIA"	"JAQL371AGENC",
"PLAZA" 	"JAQL371PLAZA",
"NOMBAN"	"JAQL371NOMBA",
"DIRBAN"  "JAQL371DIRBA",
"TELBAN"	"JAQL371TELBA",
"FAXBAN"	"JAQL371FAXBA",
"RUCBAN"	"JAQL371RUCBA"
from  CANJEINTBANPR.DATOSINICIO;

