create or replace force view jaqy554 as
select "N_NUMCOR" "JAQY554NUMCOR",
"C_CODUSU" "JAQY554CODUSU",
"N_MESPRO" "JAQY554MESPRO",
"N_ANHOPRO" "JAQY554ANHOPRO",
"N_NUMCON" "JAQY554NUMCON",
"C_ESTREG" "JAQY554ESTREG"
    from RENIEC.REDCOUS;

