create or replace force view jaqz342 as
select C_CODDPR AS JAQZ342CODDPR,
C_CODPRR AS JAQZ342CODPRR,
C_CODDIR AS JAQZ342CODDIR,
C_CODDPI AS JAQZ342CODDPI,
C_CODPRI AS JAQZ342CODPRI,
C_CODDII AS JAQZ342CODDII,
C_DESDPT AS JAQZ342DESDPT,
C_DESPRO AS JAQZ342DESPRO,
C_DESDIS AS JAQZ342DESDIS
from reniec.reteubi;

