CREATE OR REPLACE PACKAGE PQ_CR_BONOPRODUCTIVIDAD AS
     -- *****************************************************************
    -- Nombre                     : SP_CR_BONOPRODUCTIVIDAD
    -- Sistema                    : BANTOTAL
    -- Módulo                     : Créditos - Activas
    -- Versión                    : 1.0
    -- Fecha de Creación          :
    -- Autor de Creación          : ASUCASAIRE
    -- Uso                        :
    -- Estado                     : Activo
    -- Acceso                     : PRIVADO
    -- Parámetros de Entrada      :
    --
    -- Retorno                    :
    -- Fecha de Modificación      : DCASTRO
    -- Autor de la Modificación   : 2024.09.13
    -- Descripción de Modificación: Se optimizo trim agregando variable lc_analista
    --
    -- *****************************************************************
    PROCEDURE SP_CR_BONOPRODUCTIVIDAD (
        p_Usuario IN VARCHAR2,
        p_Fecha IN DATE,
        p_ANTAGENCIA OUT JAQL600.JAQL600NMES%TYPE,
        p_SALCIERRE OUT JAQL600.JAQL600SDO%TYPE,
        p_SALOTORGADO OUT JAQL600.JAQL600SOTO%TYPE,
        p_SALRECIBIDO OUT JAQL600.JAQL600SREC%TYPE,
        p_SALCASTIGADO OUT JAQL600.JAQL600SDCA%TYPE,
        p_SALJUDICIAL OUT JAQL600.JAQL600SDJU%TYPE,
        p_TANALISTA OUT VARCHAR2,
        p_TASESOR OUT VARCHAR2,
        p_CLICIERRE OUT JAQL600.JAQL600NCL%TYPE,
        p_CLIOTORGADO OUT JAQL600.JAQL600COTO%TYPE,
        p_CLIRECIBIDO OUT JAQL600.JAQL600CREC%TYPE,
        p_PCCONVENIO OUT JAQL600.JAQL600PORCO%TYPE,
        p_TPAGAR OUT JAQL600.JAQL600TOTPA%TYPE,
        p_CAGENCIA OUT JAQL600.JAQL600AGE%TYPE,
        p_DSCAGENCIA OUT VARCHAR2,
        p_DSCCATEGORIA OUT VARCHAR2,
        p_DataEncontrada OUT NUMBER
    );

    PROCEDURE SP_CR_VISTASCOMITE (
        p_Usuario IN VARCHAR2,
        p_Fecha IN DATE,
        --VISTA I
        VI_SANTERIOR OUT JAQL600.JAQL600SANT%TYPE,
        VI_CSMENSUAL OUT JAQL600.JAQL600CRSA%TYPE,
        VI_BCSALDO OUT JAQL600.JAQL600CSAL%TYPE,
        VI_TSALDO OUT JAQL600.JAQL600AUX2%TYPE,
        VI_SCIERRE OUT JAQL600.JAQL600SDO%TYPE,
        VI_MCARTERA OUT JAQL600.JAQL600MTSA%TYPE,
        VI_PCDIA OUT JAQL600.JAQL600PORDI%TYPE,
        VI_SCDIA OUT JAQL600.JAQL600SDODI%TYPE,
        VI_BCDIA OUT JAQL600.JAQL600PAGDI%TYPE,
        VI_DMES OUT JAQL600.JAQL600MTOD%TYPE,
        VI_DMICRO OUT JAQL600.JAQL600IDES%TYPE,
        VI_PDMICRO OUT JAQL600.JAQL600PDES%TYPE,
        VI_BDMICRO OUT JAQL600.JAQL600BOMI%TYPE,
        VI_TBSALDO OUT JAQL600.JAQL600PSAL%TYPE,
        VI_BRETENCION OUT JAQL600.JAQL600BARE%TYPE,
        VI_MBRETENCION OUT NUMBER,
        VI_CRETENIDOS OUT JAQL600.JAQL600MORE%TYPE,
        VI_BPRETENCION OUT JAQL600.JAQL600PRET%TYPE,
        VI_PRETENCION OUT JAQL600.JAQL600PORE%TYPE,
        VI_TBRETENCION OUT JAQL600.JAQL600CRET%TYPE,
        --VISTA II
        VII_CMANTERIOR OUT JAQL600.JAQL600CANT%TYPE,
        VII_CCMENSUAL OUT JAQL600.JAQL600CRCL%TYPE,
        VII_CCLIENTES OUT JAQL600.JAQL600CCLI%TYPE,
        VII_PECLIENTES OUT JAQL600.JAQL600ECLI%TYPE,
        VII_CLIENTES OUT JAQL600.JAQL600NCL%TYPE,
        VII_MCLIENTES OUT JAQL600.JAQL600MTCL%TYPE,
        VII_ECLIENTES OUT JAQL600.JAQL600EXCL%TYPE,
        VII_PCCLIENTES OUT JAQL600.JAQL600POCL%TYPE,
        VII_TPCLIENTES OUT JAQL600.JAQL600PCLI%TYPE,
        VII_MMANTERIOR OUT JAQL600.JAQL600PMOA%TYPE,
        VII_VMORA OUT JAQL600.JAQL600VMOR%TYPE,
        VII_PPMORA OUT JAQL600.JAQL600PMOR%TYPE,
        VII_PMORA OUT JAQL600.JAQL600PMRA%TYPE,
        VII_MMORA OUT JAQL600.JAQL600MTMR%TYPE,
        VII_TPIVARIABLE OUT JAQL600.JAQL600PVAR%TYPE,
        VII_BCONTENER OUT JAQL600.JAQL600BACO1%TYPE,
        VII_CONTENCION OUT JAQL600.JAQL600POCO1%TYPE,
        VII_MCONTENIDO OUT JAQL600.JAQL600MTCO1%TYPE,
        VII_TPICAMPANIAS OUT JAQL600.JAQL600PACO1%TYPE,
        VII_BCONTENER1 OUT JAQL600.JAQL600BACO2%TYPE,
        VII_CONTENCION1 OUT JAQL600.JAQL600POCO2%TYPE,
        VII_MCONTENIDO1 OUT JAQL600.JAQL600MTCO2%TYPE,
        VII_TPICAMPANIAS1 OUT JAQL600.JAQL600PACO2%TYPE,
        --COMITE
        VII_CCARTERA OUT JAQL600S.JAQL600STSA%TYPE,
        VII_PSaldo OUT JAQL600S.JAQL600SPSA%TYPE,
        VII_MSaldo OUT JAQL600S.JAQL600SMSA%TYPE,
        VII_CCLIENTES1 OUT JAQL600S.JAQL600STCL%TYPE,
        VII_PCLIENTES OUT JAQL600S.JAQL600SPCL%TYPE,
        VII_MCLIENTES1 OUT JAQL600S.JAQL600SMCL%TYPE,
        VII_BCONTENER2 OUT JAQL600S.JAQL600SBACO%TYPE,
        VII_CONTENCION2 OUT JAQL600S.JAQL600SPROC%TYPE,
        VII_MCONTENIDO2 OUT JAQL600S.JAQL600SMTCO%TYPE,
        VII_PCLIENTE OUT JAQL600S.JAQL600SPOCL%TYPE,
        VII_PCONTENCION OUT JAQL600S.JAQL600SPVAR%TYPE,
        --validacion
        ESCOMITE OUT NUMBER,
        Encontro OUT NUMBER,
        --ADICIONAL SIMULADOR
        p_CAV OUT JAQL600.JAQL600BARE2%TYPE

    );

    PROCEDURE SP_CR_OBTENERFECHAVALIDA(
        p_Usuario IN VARCHAR2,
        p_Fecha_Analista OUT DATE,
        p_Fecha_Comite OUT DATE,
        Encontro OUT NUMBER,
        Escomite OUT NUMBER
    );
END PQ_CR_BONOPRODUCTIVIDAD;
/

CREATE OR REPLACE PACKAGE BODY PQ_CR_BONOPRODUCTIVIDAD AS
    PROCEDURE SP_CR_BONOPRODUCTIVIDAD (
        p_Usuario IN VARCHAR2,
        p_Fecha IN DATE,
        p_ANTAGENCIA OUT JAQL600.JAQL600NMES%TYPE,
        p_SALCIERRE OUT JAQL600.JAQL600SDO%TYPE,
        p_SALOTORGADO OUT JAQL600.JAQL600SOTO%TYPE,
        p_SALRECIBIDO OUT JAQL600.JAQL600SREC%TYPE,
        p_SALCASTIGADO OUT JAQL600.JAQL600SDCA%TYPE,
        p_SALJUDICIAL OUT JAQL600.JAQL600SDJU%TYPE,
        p_TANALISTA OUT VARCHAR2,
        p_TASESOR OUT VARCHAR2,
        p_CLICIERRE OUT JAQL600.JAQL600NCL%TYPE,
        p_CLIOTORGADO OUT JAQL600.JAQL600COTO%TYPE,
        p_CLIRECIBIDO OUT JAQL600.JAQL600CREC%TYPE,
        p_PCCONVENIO OUT JAQL600.JAQL600PORCO%TYPE,
        p_TPAGAR OUT JAQL600.JAQL600TOTPA%TYPE,
        p_CAGENCIA OUT JAQL600.JAQL600AGE%TYPE,
        p_DSCAGENCIA OUT VARCHAR2,
        p_DSCCATEGORIA OUT VARCHAR2,
        p_DataEncontrada OUT NUMBER
    ) AS
    
        lc_analista char(20); --2024.09.13 dcastro
    
    
    BEGIN
        p_DataEncontrada := 0;  -- Inicializa la variable de control en 0
        lc_analista := rpad(trim(p_Usuario), 20, ' '); --2024.09.13 dcastro

        SELECT JAQL600NMES, JAQL600SDO, JAQL600SOTO,
               JAQL600SREC, JAQL600SDCA, JAQL600SDJU, JAQL600TANT,
               JAQL600TASE, JAQL600NCL, JAQL600COTO, JAQL600CREC,
               JAQL600PORCO, JAQL600TOTPA, JAQL600AGE,
               JAQL600DESAG, JAQL600DESCA, 1
        INTO p_ANTAGENCIA, p_SALCIERRE, p_SALOTORGADO,
             p_SALRECIBIDO, p_SALCASTIGADO, p_SALJUDICIAL, p_TANALISTA,
             p_TASESOR, p_CLICIERRE, p_CLIOTORGADO, p_CLIRECIBIDO,
             p_PCCONVENIO, p_TPAGAR, p_CAGENCIA,
             p_DSCAGENCIA, p_DSCCATEGORIA, p_DataEncontrada
        FROM JAQL600
        WHERE --Trim(JAQL600USU) = Trim(p_Usuario) 
            JAQL600USU = lc_analista --2024.09.13 dcastro
            AND JAQL600FPRO = p_Fecha
            AND JAQL600EST = 'S'; -- 2024.09.13 dcastro

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
                Null;
    END SP_CR_BONOPRODUCTIVIDAD;

    PROCEDURE SP_CR_VISTASCOMITE (
        p_Usuario IN VARCHAR2,
        p_Fecha IN DATE,
        --VISTA I
        VI_SANTERIOR OUT JAQL600.JAQL600SANT%TYPE,
        VI_CSMENSUAL OUT JAQL600.JAQL600CRSA%TYPE,
        VI_BCSALDO OUT JAQL600.JAQL600CSAL%TYPE,
        VI_TSALDO OUT JAQL600.JAQL600AUX2%TYPE,
        VI_SCIERRE OUT JAQL600.JAQL600SDO%TYPE,
        VI_MCARTERA OUT JAQL600.JAQL600MTSA%TYPE,
        VI_PCDIA OUT JAQL600.JAQL600PORDI%TYPE,
        VI_SCDIA OUT JAQL600.JAQL600SDODI%TYPE,
        VI_BCDIA OUT JAQL600.JAQL600PAGDI%TYPE,
        VI_DMES OUT JAQL600.JAQL600MTOD%TYPE,
        VI_DMICRO OUT JAQL600.JAQL600IDES%TYPE,
        VI_PDMICRO OUT JAQL600.JAQL600PDES%TYPE,
        VI_BDMICRO OUT JAQL600.JAQL600BOMI%TYPE,
        VI_TBSALDO OUT JAQL600.JAQL600PSAL%TYPE,
        VI_BRETENCION OUT JAQL600.JAQL600BARE%TYPE,
        VI_MBRETENCION OUT NUMBER,
        VI_CRETENIDOS OUT JAQL600.JAQL600MORE%TYPE,
        VI_BPRETENCION OUT JAQL600.JAQL600PRET%TYPE,
        VI_PRETENCION OUT JAQL600.JAQL600PORE%TYPE,
        VI_TBRETENCION OUT JAQL600.JAQL600CRET%TYPE,
        --VISTA II
        VII_CMANTERIOR OUT JAQL600.JAQL600CANT%TYPE,
        VII_CCMENSUAL OUT JAQL600.JAQL600CRCL%TYPE,
        VII_CCLIENTES OUT JAQL600.JAQL600CCLI%TYPE,
        VII_PECLIENTES OUT JAQL600.JAQL600ECLI%TYPE,
        VII_CLIENTES OUT JAQL600.JAQL600NCL%TYPE,
        VII_MCLIENTES OUT JAQL600.JAQL600MTCL%TYPE,
        VII_ECLIENTES OUT JAQL600.JAQL600EXCL%TYPE,
        VII_PCCLIENTES OUT JAQL600.JAQL600POCL%TYPE,
        VII_TPCLIENTES OUT JAQL600.JAQL600PCLI%TYPE,
        VII_MMANTERIOR OUT JAQL600.JAQL600PMOA%TYPE,
        VII_VMORA OUT JAQL600.JAQL600VMOR%TYPE,
        VII_PPMORA OUT JAQL600.JAQL600PMOR%TYPE,
        VII_PMORA OUT JAQL600.JAQL600PMRA%TYPE,
        VII_MMORA OUT JAQL600.JAQL600MTMR%TYPE,
        VII_TPIVARIABLE OUT JAQL600.JAQL600PVAR%TYPE,
        VII_BCONTENER OUT JAQL600.JAQL600BACO1%TYPE,
        VII_CONTENCION OUT JAQL600.JAQL600POCO1%TYPE,
        VII_MCONTENIDO OUT JAQL600.JAQL600MTCO1%TYPE,
        VII_TPICAMPANIAS OUT JAQL600.JAQL600PACO1%TYPE,
        VII_BCONTENER1 OUT JAQL600.JAQL600BACO2%TYPE,
        VII_CONTENCION1 OUT JAQL600.JAQL600POCO2%TYPE,
        VII_MCONTENIDO1 OUT JAQL600.JAQL600MTCO2%TYPE,
        VII_TPICAMPANIAS1 OUT JAQL600.JAQL600PACO2%TYPE,
        --COMITE
        VII_CCARTERA OUT JAQL600S.JAQL600STSA%TYPE,
        VII_PSaldo OUT JAQL600S.JAQL600SPSA%TYPE,
        VII_MSaldo OUT JAQL600S.JAQL600SMSA%TYPE,
        VII_CCLIENTES1 OUT JAQL600S.JAQL600STCL%TYPE,
        VII_PCLIENTES OUT JAQL600S.JAQL600SPCL%TYPE,
        VII_MCLIENTES1 OUT JAQL600S.JAQL600SMCL%TYPE,
        VII_BCONTENER2 OUT JAQL600S.JAQL600SBACO%TYPE,
        VII_CONTENCION2 OUT JAQL600S.JAQL600SPROC%TYPE,
        VII_MCONTENIDO2 OUT JAQL600S.JAQL600SMTCO%TYPE,
        VII_PCLIENTE OUT JAQL600S.JAQL600SPOCL%TYPE,
        VII_PCONTENCION OUT JAQL600S.JAQL600SPVAR%TYPE,
        --validacion
        ESCOMITE OUT NUMBER,
        Encontro OUT NUMBER,
        --ADICIONAL SIMULADOR
        p_CAV OUT JAQL600.JAQL600BARE2%TYPE
    ) AS
    
    lc_analista char(20); --2024.09.13 dcastro
    
    
    BEGIN
        Encontro := 0;  -- Inicializa la variable de control en 0
        ESCOMITE := 0;  -- Inicializa la variable de control en 0

        lc_analista := rpad(trim(p_Usuario), 20, ' '); --2024.09.13 dcastro        

        SELECT  JAQL600SANT,JAQL600CRSA,JAQL600CSAL,JAQL600AUX2,JAQL600SDO,
                JAQL600MTSA,JAQL600PORDI,JAQL600SDODI,JAQL600PAGDI,JAQL600MTOD,
                JAQL600IDES,JAQL600PDES,JAQL600BOMI,JAQL600PSAL,JAQL600BARE,
                5,JAQL600MORE,JAQL600PRET,JAQL600PORE,JAQL600CRET,
                JAQL600CANT,JAQL600CRCL,JAQL600CCLI,JAQL600ECLI,JAQL600NCL,
                JAQL600MTCL,JAQL600EXCL,JAQL600POCL,JAQL600PCLI,JAQL600PMOA,
                JAQL600VMOR,JAQL600PMOR,JAQL600PMRA,JAQL600MTMR,JAQL600PVAR,
                JAQL600BACO1,JAQL600POCO1,JAQL600MTCO1,JAQL600PACO1,JAQL600BACO2,
                JAQL600POCO2,JAQL600MTCO2,JAQL600PACO2,1,JAQL600BARE2

        INTO    VI_SANTERIOR,VI_CSMENSUAL,VI_BCSALDO,VI_TSALDO,VI_SCIERRE,
                VI_MCARTERA,VI_PCDIA,VI_SCDIA,VI_BCDIA,VI_DMES,
                VI_DMICRO,VI_PDMICRO,VI_BDMICRO,VI_TBSALDO,VI_BRETENCION,
                VI_MBRETENCION,VI_CRETENIDOS,VI_BPRETENCION,VI_PRETENCION,VI_TBRETENCION,
                VII_CMANTERIOR,VII_CCMENSUAL,VII_CCLIENTES,VII_PECLIENTES,VII_CLIENTES,
                VII_MCLIENTES,VII_ECLIENTES,VII_PCCLIENTES,VII_TPCLIENTES,VII_MMANTERIOR,
                VII_VMORA,VII_PPMORA,VII_PMORA,VII_MMORA,VII_TPIVARIABLE,
                VII_BCONTENER,VII_CONTENCION,VII_MCONTENIDO,VII_TPICAMPANIAS,VII_BCONTENER1,
                VII_CONTENCION1,VII_MCONTENIDO1,VII_TPICAMPANIAS1,Encontro,p_CAV

        FROM JAQL600
        WHERE --Trim(JAQL600USU) = Trim(p_Usuario) 
            JAQL600USU = lc_analista --2024.09.13 dcastro       
        AND JAQL600FPRO = p_Fecha
        AND JAQL600EST = 'S'; -- 2024.09.13 dcastro

        IF Encontro = 1 THEN
            SELECT  JAQL600STSA,JAQL600SPSA,JAQL600SMSA,JAQL600STCL,
                    JAQL600SPCL,JAQL600SMCL,JAQL600SBACO,JAQL600SPROC,
                    JAQL600SMTCO,JAQL600SPOCL,JAQL600SPVAR,1
            INTO    VII_CCARTERA,VII_PSaldo,VII_MSaldo,VII_CCLIENTES1,
                    VII_PCLIENTES,VII_MCLIENTES1,VII_BCONTENER2,VII_CONTENCION2,
                    VII_MCONTENIDO2,VII_PCLIENTE,VII_PCONTENCION,ESCOMITE

            FROM JAQL600S
            WHERE --Trim(JAQL600SUSU) = Trim(p_Usuario) 
             JAQL600SUSU = lc_analista --2024.09.13 dcastro
            AND JAQL600SFPRO = p_Fecha
            AND JAQL600SEST = 'S'; -- 2024.09.13 dcastro            
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
                Null;
    END SP_CR_VISTASCOMITE;

    PROCEDURE SP_CR_OBTENERFECHAVALIDA(
        p_Usuario IN VARCHAR2,
        p_Fecha_Analista OUT DATE,
        p_Fecha_Comite OUT DATE,
        Encontro OUT NUMBER,
        Escomite OUT NUMBER
    ) AS
    
    lc_analista char(20); --2024.09.13 dcastro
    
    BEGIN
        -- Inicializar variables
        Encontro := 0;
        Escomite := 0;
        lc_analista := rpad(trim(p_Usuario), 20, ' '); --2024.09.13 dcastro        

        -- Consultar JAQL600 para obtener la fecha de analista
        SELECT MAX(JAQL600FPRO)
        INTO p_Fecha_Analista
        FROM JAQL600
        WHERE --TRIM(JAQL600USU) = TRIM(p_Usuario);
        JAQL600USU = lc_analista --2024.09.13 dcastro
        AND JAQL600EST = 'S'; -- 2024.09.13 dcastro        

        -- Verificar si se encontró el usuario en JAQL600
        IF p_Fecha_Analista IS NOT NULL THEN
            Encontro := 1;
        END IF;

        -- Consultar JAQL600S para obtener la fecha de comité
        IF Encontro = 1 THEN
            SELECT MAX(JAQL600SFPRO)
            INTO p_Fecha_Comite
            FROM JAQL600S
            WHERE --TRIM(JAQL600SUSU) = TRIM(p_Usuario);
            JAQL600SUSU = lc_analista --2024.09.13 dcastro
            AND JAQL600SEST = 'S'; -- 2024.09.13 dcastro            

            -- Verificar si se encontró el usuario en JAQL600S
            IF p_Fecha_Comite IS NOT NULL THEN
                Escomite := 1;
            END IF;
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            -- Manejar cualquier otra excepción
            Encontro := 0;
            Escomite := 0;
    END SP_CR_OBTENERFECHAVALIDA;
END PQ_CR_BONOPRODUCTIVIDAD;
/

