CREATE OR REPLACE PROCEDURE SP_CR_INS_WEB_CONTACTAB(FECHA DATE) IS
BEGIN
--  INSERT INTO CLIENTECONSTANCIA@WCON
  INSERT INTO CLIENTECONSTANCIA--RFC
    SELECT TRIM(AQPB013NDO), AQPB013NARC, AQPB013CLA, TRUNC(SYSDATE)
      FROM AQPB013
     WHERE AQPB013EST = 'C'
       AND AQPB013FEP = FECHA;
  COMMIT;
END SP_CR_INS_WEB_CONTACTAB;
/

