CREATE OR REPLACE TRIGGER TG_AQPB620_BI99
BEFORE INSERT ON AQPB620
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB620.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB620COR  := valorSecuencia;
END;
/

