CREATE OR REPLACE TRIGGER "TG_AQPC801_BI_99"
BEFORE INSERT ON AQPC801
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPC801.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPC801CORR  := valorSecuencia;
END;
/

