CREATE OR REPLACE TRIGGER TG_AQPC589_BI_01
BEFORE INSERT ON AQPC589
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPC589.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPC589CORR  := valorSecuencia;
END;
/

