CREATE OR REPLACE TRIGGER TG_AQPB904_BI_01
BEFORE INSERT ON AQPB904
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB904.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB904CORR  := valorSecuencia;
END;
/

