CREATE OR REPLACE TRIGGER TG_AQPC448_BI01
BEFORE INSERT ON AQPC448
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPC448.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPC448COD  := valorSecuencia;
END;
/

