CREATE OR REPLACE TRIGGER TG_AQPB904A_BI_01
BEFORE INSERT ON AQPB904A
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB904A.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB904ACORR  := valorSecuencia;
END;
/

