CREATE OR REPLACE TRIGGER TG_AQPC297_BI_01
   BEFORE INSERT ON AQPC297
   FOR EACH ROW
DECLARE
   CORRELATIVO NUMBER(9) := 0;
BEGIN
   IF :NEW.AQPC297CORR IS NULL THEN
      SELECT SQ_CR_CORR_AQPC297.NEXTVAL INTO CORRELATIVO FROM DUAL;
      :NEW.AQPC297CORR := CORRELATIVO;
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END TG_AQPC297_BI_01;
/

