CREATE OR REPLACE TRIGGER TG_AQPB607D_BI99
BEFORE INSERT ON AQPB607D
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB607D.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB607DCORP  := valorSecuencia;
END;
/

