CREATE OR REPLACE TRIGGER "TG_AQPB601_BI99"
BEFORE INSERT ON AQPB601
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT /*SEQ_AQPB561*/SEQ_CR_AQPB601.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB601COD  := valorSecuencia;
END;
/

