CREATE OR REPLACE TRIGGER TG_AQPB604_BI01
BEFORE INSERT ON AQPB604
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB604.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB604CORR  := valorSecuencia;
END;
/

