CREATE OR REPLACE TRIGGER TG_AQPB605_BI01
BEFORE INSERT ON AQPB605
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB605.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB605CORR  := valorSecuencia;
END;
/

