CREATE OR REPLACE TRIGGER "TG_AQPD756_AU_01"
BEFORE INSERT ON "BANTPROD"."AQPD756"
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_CR_CORR_AQPD756.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPD756COD := valorSecuencia;                  
END;
 /* GOLDENGATE_DDL_REPLICATION */
/

