CREATE OR REPLACE TRIGGER TG_AQPB561_BI99
BEFORE INSERT ON AQPB561
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT /*SEQ_AQPB561*/SEQ_CR_AQPB561.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB561COD  := valorSecuencia;
END;
/

