CREATE OR REPLACE TRIGGER TG_AQPC551_BI_01
BEFORE INSERT ON AQPC551
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPC551.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPC551CORR  := valorSecuencia;
END;
/

