CREATE OR REPLACE TRIGGER TG_AQPB953_BI_01
BEFORE INSERT ON AQPB953
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB953.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB953COD  := valorSecuencia;
END;
/

