CREATE OR REPLACE TRIGGER TG_AQPB609_BI99
BEFORE INSERT ON AQPB609
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB609.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB609CORREL  := valorSecuencia;
END;
/

