CREATE OR REPLACE TRIGGER TG_AQPB902_BI_01
BEFORE INSERT ON AQPB902
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SEQ_CR_AQPB902.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.AQPB902CORR  := valorSecuencia;
END;
/

