CREATE OR REPLACE TRIGGER TG_DEPE67_BEF_INS
BEFORE INSERT
ON DEPE67
FOR EACH ROW
BEGIN
  IF(SUBSTR(trim(:new.DEPE67AOR),LENGTH(trim(:new.DEPE67AOR))-5,6) <> '.PAGOS') THEN
    IF(SUBSTR(trim(:new.DEPE67AOR),LENGTH(trim(:new.DEPE67AOR))-6,7) <> '.COBROS') THEN
      RAISE_APPLICATION_ERROR (-20001, 'DEPE67: '||SUBSTR(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),1,60)||', EL ARCHIVO QUE ESTA TRATANDO DE INGRESAR NO TIENE EL FORMATO .COBROS / .PAGOS');
    END IF;
  END IF;
END;
/

