CREATE OR REPLACE TRIGGER TG_DEPE65_BEF_INS
BEFORE INSERT
ON DEPE65
FOR EACH ROW
BEGIN
  IF(SUBSTR(trim(:new.DEPE65FOR),LENGTH(trim(:new.DEPE65FOR))-5,6) <> '.PAGOS') THEN
    IF(SUBSTR(trim(:new.DEPE65FOR),LENGTH(trim(:new.DEPE65FOR))-6,7) <> '.COBROS') THEN
      RAISE_APPLICATION_ERROR (-20001, 'DEPE65: '||SUBSTR(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),1,60)||', EL ARCHIVO QUE ESTA TRATANDO DE INGRESAR NO TIENE EL FORMATO .PAGOS');
    END IF;
  END IF;
END;
/

