CREATE OR REPLACE TRIGGER TG_JAQL493_BI_01
BEFORE INSERT ON JAQL493
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL493CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL493CORR2  := valorSecuencia;
END;
/

