CREATE OR REPLACE TRIGGER TG_JAQZ761_BI_01
BEFORE INSERT ON JAQZ761
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQZ761CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQZ761CORR2  := valorSecuencia;
END;
/

