CREATE OR REPLACE TRIGGER TG_JAQL478_BI_01
BEFORE INSERT ON JAQL478
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL478CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL478CORR2  := valorSecuencia;
END;
/

