CREATE OR REPLACE TRIGGER TG_JAQL496_BI_01
BEFORE INSERT ON JAQL496
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL496CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL496CORR2  := valorSecuencia;
END;
/

