CREATE OR REPLACE TRIGGER TG_JAQY840_BI_01
BEFORE INSERT ON JAQY840
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQY840CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQY840CORR2  := valorSecuencia;
END;
/

