CREATE OR REPLACE TRIGGER TG_JAQL494_BI_01
BEFORE INSERT ON JAQL494
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL494CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL494CORR2  := valorSecuencia;
END;
/

