CREATE OR REPLACE TRIGGER TG_JAQL819B_BI_01
BEFORE INSERT ON JAQL819B
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL819BCORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL819BCORR2  := valorSecuencia;
END;
/

