CREATE OR REPLACE TRIGGER TG_JAQL976_BI_01
BEFORE INSERT ON JAQL976
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL976CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL976CORR2  := valorSecuencia;
END;
/

