CREATE OR REPLACE TRIGGER TG_JAQL497_BI_01
BEFORE INSERT ON JAQL497
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL497CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL497CORR2  := valorSecuencia;
END;
/

