CREATE OR REPLACE TRIGGER TG_JAQY841_BI_01
BEFORE INSERT ON JAQY841
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQY841CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQY841CORR2  := valorSecuencia;
END;
/

