CREATE OR REPLACE TRIGGER TG_JAQL819C_BI_01
BEFORE INSERT ON JAQL819C
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL819CCORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL819CCORR2  := valorSecuencia;
END;
/

