CREATE OR REPLACE TRIGGER TG_JAQZ765_BI_01
BEFORE INSERT ON JAQZ765
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQZ765CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQZ765CORR2  := valorSecuencia;
END;
/

