CREATE OR REPLACE TRIGGER TG_JAQL495_BI_01
BEFORE INSERT ON JAQL495
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL495CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL495CORR2  := valorSecuencia;
END;
/

