CREATE OR REPLACE TRIGGER TG_JAQL819A_BI_01
BEFORE INSERT ON JAQL819A
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQL819ACORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQL819ACORR2  := valorSecuencia;
END;
/

