CREATE OR REPLACE TRIGGER TG_JAQZ764_BI_01
BEFORE INSERT ON JAQZ764
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQZ764CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQZ764CORR2  := valorSecuencia;
END;
/

