CREATE OR REPLACE TRIGGER TG_JAQY842_BI_01
BEFORE INSERT ON JAQY842
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SQ_MP_JAQY842CORR2.NEXTVAL INTO valorSecuencia FROM DUAL;
:new.JAQY842CORR2  := valorSecuencia;
END;
/

