create or replace force view v_fsd010 as
select "PGCOD","AOMOD","AOSUC","AOMDA","AOPAP","AOCTA","AOOPER","AOSBOP","AOTOPE","AOFVAL","AOFVTO","AOPZO","AOTTAS","AOTASA","AOTMOR","AOTTAC","AOTASC","AOTDIA","AOTVTO","AOTANO","AOTINT","AODREV","AOIMP","AOPRE","AOPRE1","AOTCBI","AOTCBI1","AOARB","AOARB1","AOMD","AOMD1","AONUME","AOFNUM","AOAFIV","AOCBCU","AOSTAT","AOAVIS","AOPLUS","AOEVEN","AOFE99","AOCLTCOD","AOPERIOD" from fsd010
union all
select "PGCOD","AOMOD","AOSUC","AOMDA","AOPAP","AOCTA","AOOPER","AOSBOP","AOTOPE","AOFVAL","AOFVTO","AOPZO","AOTTAS","AOTASA","AOTMOR","AOTTAC","AOTASC","AOTDIA","AOTVTO","AOTANO","AOTINT","AODREV","AOIMP","AOPRE","AOPRE1","AOTCBI","AOTCBI1","AOARB","AOARB1","AOMD","AOMD1","AONUME","AOFNUM","AOAFIV","AOCBCU","AOSTAT","AOAVIS","AOPLUS","AOEVEN","AOFE99","AOCLTCOD","AOPERIOD" from fsd010 where 1=2 with read only;

