create or replace force view v_fsd002 as
select "PFPAIS","PFTDOC","PFNDOC","PFAPE1","PFAPE2","PFNOM1","PFNOM2","PFEBCO","PFFIBC","PFCANT","PFFNAC","PFECIV","PFPNAC","PFLNAC","PFCLEG","PFFLEG","PFFAL","PFFFAL","PFCAPL","PFFANT","PFEPAT","PFFPEP" from FSD002 union all select "PFPAIS","PFTDOC","PFNDOC","PFAPE1","PFAPE2","PFNOM1","PFNOM2","PFEBCO","PFFIBC","PFCANT","PFFNAC","PFECIV","PFPNAC","PFLNAC","PFCLEG","PFFLEG","PFFAL","PFFFAL","PFCAPL","PFFANT","PFEPAT","PFFPEP" from FSD002 where 1=2 with read only;

