create or replace force view v_fsh021 as
select "SBCOD","SBMOD","SBSUC","SBMDA","SBPAP","SBCTA","SBOPER","SBSBOP","SBTOPE","SBFECH","SBSDO","SBGIRA","SBCHQDEV","SBSDO1","SBSDO2","SBCDEB","SBCCRE","SBTDEB","SBTCRE","SBCMOV","SBTMIN","SBTMAX","SBTPRO" from FSH021 union all select "SBCOD","SBMOD","SBSUC","SBMDA","SBPAP","SBCTA","SBOPER","SBSBOP","SBTOPE","SBFECH","SBSDO","SBGIRA","SBCHQDEV","SBSDO1","SBSDO2","SBCDEB","SBCCRE","SBTDEB","SBTCRE","SBCMOV","SBTMIN","SBTMAX","SBTPRO" from FSH021 where 1=2 with read only;

