create or replace force view v_fsd011 as
select "PGCOD","SCSUC","SCRUB","SCMDA","SCPAP","SCCTA","SCOPER","SCSBOP","SCTOPE","SCMOD","SCFCON","SCFVAL","SCFVTO","SCFULM","SCPZO","SCSDO","SCSDOH","SCSEGM","SCFUNC","SCSTAT","SCCC","SCTIT","SCCAP","SCPLZO","SCGRU" from fsd011
union all
select "PGCOD","SCSUC","SCRUB","SCMDA","SCPAP","SCCTA","SCOPER","SCSBOP","SCTOPE","SCMOD","SCFCON","SCFVAL","SCFVTO","SCFULM","SCPZO","SCSDO","SCSDOH","SCSEGM","SCFUNC","SCSTAT","SCCC","SCTIT","SCCAP","SCPLZO","SCGRU" from fsd011 where 1=2 with read only;

