create or replace force view v_fsd008 as
select "PGCOD","CTNRO","CTNOM","CTRESI","CTEJCT","CTCCLI","CTFALT","CTRCOR","CTCORP","CTPIN","SECCOD","CTIFIN","CTNGTE","CTCBCU","CTNROI","CTCRIE","CTEMPL","CTPROV","CTFBAJ","CTFCNF","CTIMAB","CTSEGM" from FSD008 union all select "PGCOD","CTNRO","CTNOM","CTRESI","CTEJCT","CTCCLI","CTFALT","CTRCOR","CTCORP","CTPIN","SECCOD","CTIFIN","CTNGTE","CTCBCU","CTNROI","CTCRIE","CTEMPL","CTPROV","CTFBAJ","CTFCNF","CTIMAB","CTSEGM" from FSD008 where 1=2 with read only;

