create or replace force view v_fst017 as
select "PGCOD","PGNOM","PGSUC","PGMNAC","PGMDBC","PGDUSA","PGDUSB","PGFBCE","RPCCYG","PGVUTI","PGVUTM","PGVUTV","PGPOME","PGPOMN","PGIVME","PGIVM2","PGCCXO","PGCCXS","PGCAXO","PGCAXS","PGAPOD","PGCLTE","PGNBCO","PGMODC","PGMOCC","PGMOCA","PGSIGL","PGAJMN","PGFCIE","PGFAPE","PGLIMM","PGALTP","PGSUC0","PGREFV","PGBBTT","PGCEFL","PGCSN1","PGCSN2","PGCSN3","PGCSN4","PGCSN5","PGFMES","PGPLAT","PGHIOL","PGADFI","PGPAIS","PGIDIO","PGNIV","PGRUBR" from FST017
union all
select "PGCOD","PGNOM","PGSUC","PGMNAC","PGMDBC","PGDUSA","PGDUSB","PGFBCE","RPCCYG","PGVUTI","PGVUTM","PGVUTV","PGPOME","PGPOMN","PGIVME","PGIVM2","PGCCXO","PGCCXS","PGCAXO","PGCAXS","PGAPOD","PGCLTE","PGNBCO","PGMODC","PGMOCC","PGMOCA","PGSIGL","PGAJMN","PGFCIE","PGFAPE","PGLIMM","PGALTP","PGSUC0","PGREFV","PGBBTT","PGCEFL","PGCSN1","PGCSN2","PGCSN3","PGCSN4","PGCSN5","PGFMES","PGPLAT","PGHIOL","PGADFI","PGPAIS","PGIDIO","PGNIV","PGRUBR" from FST017 where 1=2 with read only;

