create or replace force view v_reprog_form_mype as
select "DNICLIENTE","SOLICITUD","BAL_CAJABANCOS","BAL_INVENTARIO","BAL_MAQEQUI","BAL_INMUEBLES","BAL_OTROS","BAL_TOTALACTIVO","BAL_TOTALPASIVO","BAL_PATRIMONIO","ACT_VENTAS","ACT_COVENTAS","ACT_COOPERATIVO","ACT_GAFINANCIERO","ACT_RESULEMP","ACT_GASTOSFIN","ACT_GASTOSFAM","ACT_RESULTADONETO","ACT_RATIOPOSTCOV","M12_VENTAS","M12_COVENTAS","M12_COOPERATIVO","M12_GAFINANCIERO","M12_RESULEMP","M12_GASTOSFIN","M12_GASTOSFAM","M12_RESULTADONETO","M12_RATIOPOSTCOV","ACTECONPOSTCOVID" from REPROG_FORM_MYPE/*@cmr*/;

