create or replace force view v_reprog_form_cons as
select "DNICLIENTE","SOLICITUD","ACT_INGRESOBRUTO","ACT_INGRESONETO","ACT_GASTOFAMILIAR","ACT_ENDEUDAMIENTO","ACT_TOTALEGRESOS","ACT_RESULTNETO","ACT_RATIOPOSTCOVID","ACT_EFECTIVO","M12_INGRESOBRUTO","M12_INGRESONETO","M12_GASTOFAMILIAR","M12_ENDEUDAMIENTO","M12_TOTALEGRESOS","M12_RESULTNETO","M12_RATIOPOSTCOVID","ACTECONPOSTCOVID" from REPROG_FORM_CONS/*@cmr*/;

