create or replace force view v_reprog as
select "DNICLIENTE",
"SOLICITUD",
"CUENTAOPERACION",
"CODANALISTA",
"FECHACARGA",
"FECHALIMITE",
"TIPOCREDITO",
"PRIORIDAD",
"ESTADOSOLICITUD",
"AFECTACIONINGRESO",
"INICIADOANALISTA",
"INICIADOCLIENTE",
"FECENPROCESO",
"FECPENDBT",
"FECTERMINADO",
"FECCANCELADO",
"TIPOREPROGRAMACION" from REPROG/*@cmr*/;

